# Generated by Django 5.0.3 on 2024-08-11 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotification',
            name='sent_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
