# Generated by Django 5.0.3 on 2024-08-11 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0003_remove_broadcastnotification_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastnotification',
            name='broadcast_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
