# Generated by Django 5.0.3 on 2024-08-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0004_alter_broadcastnotification_broadcast_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastnotification',
            name='broadcast_on',
            field=models.DateTimeField(),
        ),
    ]
