# Generated by Django 5.0.3 on 2024-08-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0006_remove_broadcastnotification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotification',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
