# Generated by Django 5.0.3 on 2024-04-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='water_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('WaterLevel', models.FloatField()),
                ('Rainfall', models.FloatField()),
                ('Drawdown', models.FloatField()),
            ],
        ),
    ]
