# Generated by Django 5.0.3 on 2024-04-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='business_zones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Business_zones', models.CharField(max_length=20)),
                ('Supply_volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Bill_volume', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='water_data',
            name='Drawdown',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='water_data',
            name='Rainfall',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='water_data',
            name='WaterLevel',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
