# Generated by Django 5.0.3 on 2024-04-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_support', '0002_business_zones_alter_water_data_drawdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_zones',
            name='Business_zones',
            field=models.CharField(choices=[('Araneta-Libis', 'Araneta-Libis'), ('Elliptical', 'Elliptical'), ('San Juan', 'San Juan'), ('Tandang sora', 'Tandang sora'), ('Timog', 'Timog'), ('Up-Katipunan', 'Up-Katipunan')], max_length=20),
        ),
    ]
