# Generated by Django 5.0.3 on 2024-05-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_support', '0004_alter_water_data_drawdown_alter_water_data_rainfall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rainfall_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Rainfall', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('MaxTemp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('MinTemp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('MeanTemp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('WindSpeed', models.IntegerField(null=True)),
                ('WindDirection', models.IntegerField(null=True)),
                ('RelativeHumidity', models.IntegerField(null=True)),
            ],
        ),
    ]
