# Generated by Django 5.0.3 on 2024-09-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decision_support', '0006_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
