# Generated by Django 5.0.3 on 2024-09-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decision_support', '0007_delete_permission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='business_zones',
            new_name='business_zones_data',
        ),
    ]
